// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywghefarrcwbnraqyfgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3Z2hlZmFycmN3Ym5yYXF5ZmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNDgxMzQsImV4cCI6MjA3NDgyNDEzNH0.oSm-CvlFFmaMEzJMLRdBYTLiZUG55DI7vMzZoRGWlho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
